apiVersion: v1
kind: Service
metadata:
    labels:
        app: simple-gis-web
    name: simple-gis-web-service
spec:
    type: LoadBalancer
    ports:
        -   name: simple-gis-web-port
            port: 8045
            protocol: TCP
            targetPort: 80
    selector:
        app: simple-gis-web
